# Generated by Django 4.0.3 on 2022-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_imagemodelssd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedestrianDetectSSD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModelssd',
        ),
    ]
