# Generated by Django 4.0.3 on 2022-05-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_pedestriandetectssd_delete_imagemodelssd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedestriandetectssd',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='pedestriandetectssd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedestriandetectssd',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='image'),
        ),
    ]
