# Generated by Django 4.0.3 on 2022-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_pedestriandetectssd_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pedestriandetectssd',
            options={},
        ),
    ]
